---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="alpine" tag="latest"
    - image="alpine" tag="edge"
    - image="amazonlinux" tag="1"
    - image="centos" tag="7"
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="debian" tag="bullseye"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="xenial"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - function retry { counter=0 ; until "$@" ; do exit=$? ; counter=$(($counter + 1)) ; if [ $counter -ge 3 ] ; then return $exit ; fi ; done ; return 0; } retry tox

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: "o/+WFpbq09cDQY3NGlyQ886AdOwLrxNZG3Z2jWz4ucbrXr4Ba1dk0pPi9XbuqVks8p/h5brvZ5UPsccxI1yMGGFBi5NunalwG4nfgj4/3JakaQy4nTHW0nAF6V+1wD1zIFDwxc0Brbx2Uq8S1cyBuBO8xd4TUldsyDyb6ybQXWoc+JHjYcbnIB0F+Cpe+5red5OJeIgoSsQv1GFu5QNH2l8CR2WVaBwvRIw9XnlfhcNI8iHizr3K1NOZNWJhcV7UqCrt5S4EcZxOZVpt+Vhkdm1f6qnAQobtxWnK1aLIcv/f+mSGohYqsuzI9+TlgGRIKAG3pffpFu+xBjwPucipTMhhY1k+wfMyh0Kdeb/3kqpqXJECUqcDSl0XMWJrPMKJK9rnsxQlL3udXEohf1LoFESicoS5dsqBwFK6odQ2QoW7ki/XgSt4dhTCat6Soo2rGDcS5ILMjV4hnyJPPMAOlHV8EeuQyZnseo2o25YjSrqIsgnxfSSuUuPXj8qFtnPvx10a8jM9lFPZRRmvUWPzQ7cVZZpu811W79naMO/1raAlEGde8J+7KAbEL6uaLGxn3H79gUMtt1YXTNBKx16azInU/L1NNkn+6ur74EQDnlBEhYFUvkwDaL9OcWM/R2A+U+j6JZMhsIsG+T49hj+MXEL78qPkBCRDtOGNR5vWieQ="
  email: false
