---
# handlers file for xrdp
- name: restart xrdp
  block:
    - name: using service
      service:
        name: "{{ xrdp_service }}"
        state: restarted
  rescue:
    - name: collect information
      command: "{{ item }}"
      register: xrdp_collect_information
      loop:
        - journalxtl -xe
        - systemctl status {{ xrdp_service }}
    - name: show information
      debug:
        msg: "{{ item }}"
      loop: "{{ xrdp_collect_information.results }}"
